version: "3.3"
services:
  db_mysql:
    image: mysql:latest
    restart: always
    container_name: shop_on_sofa
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=shop_on_sofa
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./mysql-data:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025